CREATE TABLE IF NOT EXISTS "Information" (
  "Information Id" SERIAL PRIMARY KEY,
  "District Municipality" VARCHAR(255),
  "Local Municipality" VARCHAR(255),
  "Ward" VARCHAR(255),
  "Name of Area/Location (House No./Isigodi)" VARCHAR(255),
  "Specify street address where possible/applicable" VARCHAR(255),
  "Ward Councillor" VARCHAR(255),
  "Ward Councillor Number" VARCHAR(255),
  "Date of Incident" VARCHAR(255),
  "Date Reported" VARCHAR(255),
  "Date Responded" VARCHAR(255),
  "Time of Incident" VARCHAR(255),
  "Time Reported" VARCHAR(255),
  "Time Responded" VARCHAR(255),
  "Longitude (E)" VARCHAR(255),
  "Latitude (S)" VARCHAR(255),
  "Early warning received (Yes/No)" VARCHAR(255),
  "Type of Incident" VARCHAR(255),
  "Other Incident" VARCHAR(255),
  "Cause of Incident" VARCHAR(255),
  "Other Cause" VARCHAR(255),
  "Name of Family" VARCHAR(255),
  "Head of Household" VARCHAR(255),
  "Identity Number" VARCHAR(255),
  "Contact Number" VARCHAR(255),
  "Alternitive Number" VARCHAR(255),
  "Number of household member(s)" VARCHAR(255),
  "Senior Citizen (Pensioners)" VARCHAR(255),
  "Woman" VARCHAR(255),
  "Men" VARCHAR(255),
  "Children (under 18 years)" VARCHAR(255),
  "People with Disability" VARCHAR(255),
  "Any Injured" VARCHAR(255),
  "No. of injuries" VARCHAR(255),
  "Emergency Assistance Required" VARCHAR(255),
  "Evacuated To" VARCHAR(255),
  "Mode of Transport" VARCHAR(255),
  "Any Fatalities" VARCHAR(255),
  "No. of Fatalities" VARCHAR(255),
  "Fatalities Confirmed" VARCHAR(255),
  "Any Scholars Effeccted" VARCHAR(255),
  "Textbook Damage" VARCHAR(255),
  "Any Lost Document" VARCHAR(255),
  "Lost Document Amount" VARCHAR(255),
  "Items Lost" VARCHAR(255),
  "No. of structures in a household" VARCHAR(255),
  "No. of partially damaged structures" VARCHAR(255),
  "Any Homeless" VARCHAR(255),
  "No. of Homeless" VARCHAR(255),
  "Temporal Accomidation" VARCHAR(255),
  "Other Damages" VARCHAR(255),
  "No. of Mud house/structure" VARCHAR(255),
  "No. of shack/ informal settlement structure" VARCHAR(255),
  "No. of totally destroyed structures" VARCHAR(255),
  "Number of RDP" VARCHAR(255),
  "Roof Damages" VARCHAR(255),
  "structuralDamages" VARCHAR(255),
  "Essential Services Damaged" VARCHAR(255),
  "Assistance Issued" VARCHAR(255),
  "Temporal Shelter" VARCHAR(255),
  "Soup Kitchen" VARCHAR(255),
  "Food Parcels" VARCHAR(255),
  "Tents" VARCHAR(255),
  "Blankets" VARCHAR(255),
  "Sponges" VARCHAR(255),
  "Plastic Sheeting" VARCHAR(255),
  "Stove" VARCHAR(255),
  "Pots" VARCHAR(255),
  "Other" VARCHAR(255),
  "Type of Intervention" VARCHAR(256),
  "Infrastructure" VARCHAR(255),
  "Livestock" VARCHAR(255),
  "Croplosses" VARCHAR(255),
  "Soil Degradation" VARCHAR(255),
  "Job Opportunities" VARCHAR(255),
  "Veld" VARCHAR(255),
  "Mattresses" VARCHAR(255),
  "Repair" VARCHAR(255),
  "Other Intervention" VARCHAR(255),
  "Notes" VARCHAR(255),
  "No. of formal house/structure" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "Children" (
  "Id" SERIAL PRIMARY KEY,
  "Information Id" INTEGER,
  "Name" VARCHAR(45),
  "Birthdate" VARCHAR(45),
  "Gender" VARCHAR(45),
  "Age" VARCHAR(45),
  "School" VARCHAR(45),
  "Grade" VARCHAR(45),
  "Shoe Size" VARCHAR(45),
  "Uniform Size" VARCHAR(45),
  "Additional Information" VARCHAR(45),
  FOREIGN KEY ("Information Id") REFERENCES "Information"("Information Id")
);

CREATE TABLE IF NOT EXISTS "Pictures" (
  "Id" SERIAL PRIMARY KEY,
  "Information Id" INTEGER,
  image1 VARCHAR(500),
  image2 VARCHAR(500),
  image3 VARCHAR(500),
  image4 VARCHAR(500),
  image5 VARCHAR(500),
  image6 VARCHAR(500),
  image7 VARCHAR(500),
  image8 VARCHAR(500),
  image9 VARCHAR(500),
  image10 VARCHAR(500),
  FOREIGN KEY ("Information Id") REFERENCES "Information"("Information Id")
);

